[build]
  command = "CI=false npm run build"
  publish = "build"

# Handle client-side routing with React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  CI = "false" 